---
- name: awxtest
  hosts: all
  become: yes
  tasks:
    - name: Create Docker service
      docker_swarm_service:
        name: test1
        state: present
        replicas: 3
        placement:
          constraints:
            - "node.role==worker"
        env: 
          - "WITH_REGISTRY_AUTH=true"
          - "PUBLISHED_PORT=8001" 
          - "TARGET_PORT=80"

        image: "nginx:latest"
